### ISSUE TITLE
Respira?

### ISSUE THREAD

**Issue by renan-eccel** [caiopo/quibe-bot#4]
Qiibebot, me responde. Não aguento mais ser ignorado por você no telegram. Te amo tanto. Não faz isso comigo.

**Comment by caiopo** [comment]
Oi, eu fui pego num bug que acidentalmente deletou 70k de contas no telegram, e como o bot tá associado à minha conta, ele foi junto.
Minha conta e o bot já foram restaurados, mas eu preciso reconfigurar ele pra que ele volte a funcionar. Farei isso em breve. :)

**Comment by caiopo** [comment]
Pronto, tá vivo o menino.

Desculpa o spam de cardápio que ele deve ter te mandado. :laughing:

**Comment by renan-eccel** [comment]
Muito obrigado pela atenção @caiopo!
Todos os integrantes do meu grupo de agendamento de encontros no RU agradecem a sua iniciativa ao criar e manter o quibebot!
Muito obrigado.
:crown:

**Comment by caiopo** [comment]
Imagina! :heart:
